version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - aws sts get-caller-identity
      - cd Terraform
      - terraform --version
      - terraform init -input=false
      - terraform validate
      - terraform plan -lock=false -input=false -var=AWS_ACCESS_KEY_ID=$ACCESS_KEY -var=AWS_SECRET_ACCESS_KEY=$SECRET -var=GITHUB_PAT=$GITHUB_PAT